datguyrhy/MQ

config/routes.rb

Added root route in routes file to point to posts index page

Added root route

---

Gemfile
Gemfile.lock
app/controllers/posts_controller.rb
app/models/post.rb
app/models/restaurant.rb
app/views/posts/index.html.erb
db/migrate/20191111101932_create_posts.rb
db/seeds.rb

-added post controllers
-modified model relationship between restaurant & posts
-added seeds file for restaurant & posts

-Added basic post index views and seeding

---

db/migrate/20191113011742_create_customer_profiles.rb

fixed reference => references spelling error in customer_profile migration file

fixed reference => references 

---

app/controllers/customer_profiles_controller.rb
app/models/customer_profile.rb
app/views/customer_profiles/edit.html.erb
app/views/customer_profiles/new.html.erb
app/views/layouts/application.html.erb
app/views/orders/index.html.erb
app/views/orders/new.html.erb
app/views/orders/show.html.erb
db/schema.rb

**made changes to customer_profiles**
-added edit function for customer profile
-added views for edit
-changed orders/new path
**layout**
-edited global nav to reflect profile
-changed new order path

**made changes to customer_profiles**

---

app/controllers/orders_controller.rb
app/controllers/posts_controller.rb
app/models/order.rb
app/views/orders/new.html.erb
app/views/posts/show.html.erb

Outstanding: Calculate total amount for each order and apply discount
----
In this request:
- Add orders for each post with total payable for each order
- Fixed duplicate checkbox show on new order form
- Fixed redirection path after adding new order and back link on new order form

Add order discount

---

app/controllers/customer_profiles_controller.rb
app/models/customer.rb
app/models/customer_profile.rb
app/views/customer_profiles/edit.html.erb
app/views/customer_profiles/new.html.erb
app/views/customer_profiles/show.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/layouts/application.html.erb

-added edit function
-added show
-basic layout setup
-changes to model to include posts and orders

customer_profile add

---

app/controllers/orders_controller.rb
app/models/order.rb
app/views/posts/show.html.erb

Added function to calculate total amount for each order and store

Update orders related functions

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/customer_profiles.scss
app/assets/stylesheets/user_profiles.scss
app/controllers/customer_profiles_controller.rb
app/views/customer_profiles/show.html.erb
app/views/layouts/application.html.erb
app/views/orders/show.html.erb
app/views/posts/show.html.erb

-reworked Post new layout
-added order to customer profile page
- changed navbar layout
- changed customer_profile model
- set layout for post show with table.

Aded controllers for customer_profile pages & CSS layout

---

app/controllers/orders_controller.rb
app/models/menu_item.rb
app/models/restaurant.rb
app/views/orders/new.html.erb
app/views/orders/show.html.erb
app/views/posts/show.html.erb

Orders Controller:
- Save discounted price for each order if total amount of all orders for the post is more than or equal to minimum spending of the selected restaurant
- Updated show method to get order by order ID
- Updated new method to show get only menu items for the selected restaurant. 
- Updated redirect path after saving order.
Show Post View:
- Tidy up information to display to users
- Added link to show details for each order ID
New Order View Page:
Updated to show menu items for that selected restaurant, else show no menu available
Show Order View Page:
- Added order confirmation page
- Added created at and expected delivery time. Fixed back to path parameter.
Menu Item Model:
- Added foreign key relationship to restaurant
Restaurant Model:
- Added foreign key relationship to …

Add discount for each order; enhanced new and show order page, show post page; update model relationship

---

app/assets/stylesheets/posts.scss
app/views/posts/index.html.erb
db/schema.rb

Added responsive display for Post( cards)

posts index card display

---

app/controllers/customer_profiles_controller.rb
app/controllers/orders_controller.rb
app/controllers/posts_controller.rb

Add user authentication to post, order, customer profile controllers

Add user authentication to post, order, customer profile controllers

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/devise.scss
app/views/customer_profiles/show.html.erb
app/views/devise/confirmations/new.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_error_messages.html.erb
app/views/devise/shared/_links.html.erb
app/views/layouts/application.html.erb

added layouts for logins & signup
changed error  messages layout

add layout for login, signup & changed error messages

---

app/views/posts/show.html.erb

Show Post Controller:
- Display link text as 'Add Order' if logged in user is the poster
- Display link text as 'Join Order' if logged in user is not the poster

Show different link text depending on logged in user

---

app/controllers/application_controller.rb

Application Controller:
- Fix redirect user to post index if customer profile exists

Fix redirect user to post index if customer profile exists

---

app/controllers/customer_profiles_controller.rb
app/models/customer_profile.rb

-changed update controller
>>> find customers_params

bug fix for customer profile edit

---

app/controllers/orders_controller.rb
app/controllers/posts_controller.rb
app/models/post.rb
app/views/posts/index.html.erb
app/views/posts/show.html.erb
db/schema.rb

Orders Controller: 
- Move check for discount logic to post model/view
Post Model:
- Added function to check for discount eligibility
Post Controller:
- Update index, create and show methods
Post Show View:
- Updated variable name and update discount value to true if eligible
- Added logic to hide add orders if minimum spending has been achieved for the post
Post Index View:
- Removed additional else at the very last line

Refactor check for discount

---

app/controllers/customer_profiles_controller.rb
app/controllers/orders_controller.rb
app/controllers/posts_controller.rb
app/models/post.rb
app/views/posts/index.html.erb
app/views/posts/show.html.erb
db/schema.rb

Customer Profile Controller:
- Updated create method to set name to email if no name entered

Set customer name to email if left blank

---

app/views/customer_profiles/show.html.erb
app/views/posts/show.html.erb

Posts Show View, Customer Profile Show View
- Fix view order path to posts/:post_id/orders/:id

Fix view order details path

---

app/assets/javascripts/application.js
app/assets/javascripts/script.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/posts.scss
app/views/customer_profiles/new.html.erb
app/views/customer_profiles/show.html.erb
app/views/layouts/application.html.erb
app/views/posts/index.html.erb
app/views/posts/show.html.erb

Adjusted table (headings, font size, etc..)
Adjusted link routes to correct paths
Adjusted stylesheet for post index image sizing
Adjust customer profile creation layout
adjusted footer

Adjusted global-nav layout v3.

---

db/migrate/20191111101932_create_posts.rb
db/schema.rb

Create Posts migration file
- Added default value for discount column

Fix default discount value for seeded posts

---

app/views/customer_profiles/new.html.erb
app/views/layouts/application.html.erb
app/views/orders/new.html.erb
db/schema.rb

adjusted order list layout to be justified
changed global nav 
- customer name to be link
-profile link removed 
- login and logout now bold

Order list

---

app/assets/stylesheets/application.scss
app/views/customer_profiles/index.html.erb
app/views/customer_profiles/new.html.erb
app/views/customer_profiles/show.html.erb
app/views/layouts/application.html.erb
app/views/orders/index.html.erb
app/views/orders/show.html.erb
app/views/posts/show.html.erb
db/schema.rb

added layout changes
removed notices from all relevant pages
adjusted size of logo

added logo
